apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-deployment
spec:
  schedule: "*/1 * * * *"  # A cada 1 minutos
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - "kubectl rollout restart deployment contact-api"
          restartPolicy: Never
