apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-api
spec:
  selector:
    matchLabels:
      app: contact-api
  replicas: 1
  template:
    metadata:
      labels:
        app: contact-api
    spec:
      containers:
        - name: contact-api
          image: ppagotto/tc-contact-api:latest
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
          - name: https
            containerPort: 8083
          env:
          - name: ConnectionStrings__techchallenge01
            valueFrom:
              secretKeyRef:
                name: database-secret-config
                key: connectionstring
          - name: RabbitMQConnection__Host
            valueFrom:
              secretKeyRef:
                name: database-secret-config
                key: rabbitmqhost
          - name: RabbitMQConnection__Username
            valueFrom:
              secretKeyRef:
                name: database-secret-config
                key: rabbitmqusername
          - name: RabbitMQConnection__Password
            valueFrom:
              secretKeyRef:
                name: database-secret-config
                key: rabbitmqpassword 
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: contact-api
spec:
  type: ClusterIP
  selector:
    app: contact-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8083
    targetPort: 8083
